# Base configs
baseurl: "http://sarahwrobelsinclair.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Happy Birthday Sarah! Click here!"
subtitle: "I love you sister!"
author: "Jonathan Wrobel"
header:
 title: "Sarah's Birthday"
 subtitle: "by her big bro"
footer:
 name: "Hey "
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:

