# Base configs
baseurl: ""
url: "https://localhost/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Happy Birthday Sarah!"
subtitle: "I love you sister!"
author: "Jonathan Wrobel"
header:
 title: "Sarah's Birthday Gift"
 subtitle: "by her big bro"
footer:
 name: "Hey "

